#! /usr/bin/env racket
#lang racket
(require "../parser/parser.rkt"
         "../program_representation/racket-synthesis.rkt"
         racket/port
         parser-tools/lex
         (prefix-in re- parser-tools/lex-sre)
         parser-tools/yacc)

(define args (vector->list (current-command-line-arguments)))

(define in (open-input-file (first args)))
(define program (port->string in))
(close-input-port in)

(define lst (let*
                ((test-program program)
                 (input (open-input-string test-program)))
              (translate (simple-math-parser (lex-this simple-math-lexer input)))))

(display (translate-to-c lst))

